create table game (
	game_id varchar(30) not null primary key,
	game_type varchar(1) not null,
	local_game_time varchar(10),
	game_pk integer,
	game_time_et varchar(10),
	home_sport_code varchar(10),
	home_id integer,
	home_team_code varchar(3),
	home_fname varchar(30),
	home_sname varchar(30),
	home_wins integer,
	home_loss integer,
	away_id integer,
	away_team_code varchar(3),
	away_fname varchar(50),
	away_sname varchar(50),
	away_wins integer,
	away_loss integer,
	status_ind char(1),
	"date" date,
	day varchar(3),
	stadium_id integer,
	stadium_name varchar(40),
	stadium_location varchar(30)
);

create table atbat (
	/* custom fields */
	game_id varchar(30) not null,
	half varchar(10),
	inning integer,
	/* gameday fields */
	num integer not null,
	b integer,
	s integer,
	o integer,
	score char(1),
	batter integer,
	stand char(1),
	b_height varchar(5),
	pitcher integer,
	p_throws char(1),
	des varchar(500),
	des_es varchar(500),
	event varchar(200),
	event2 varchar(200),
	event3 varchar(200),
	event4 varchar(200),
	home_team_runs integer,
	away_team_runs integer,
	start_tfs integer,
	start_tfs_zulu varchar(25),
	primary key (game_id, num)
);

create table pitch (
	/* custom fields */
	game_id varchar(30) not null,
	num integer,
	pitcher integer,
	batter integer,
	b integer,
	s integer,
	/* gameday fields */
	des varchar(100),
	id integer,
	type varchar(3) not null,
	x decimal(7,3),
	y decimal(7,3),
	on_1b integer,
	on_2b integer,
	on_3b integer,
	sv_id varchar(20),
	start_speed decimal(7,3),
	end_speed decimal(7,3),
	sz_top decimal(7,3),
	sz_bot decimal(7,3),
	pfx_x decimal(7,3),
	pfx_z decimal(7,3),
	px decimal(7,3),
	pz decimal(7,3),
	x0 decimal(7,3),
	y0 decimal(7,3),
	z0 decimal(7,3),
	vx0 decimal(7,3),
	vy0 decimal(7,3),
	vz0 decimal(7,3),
	ax decimal(7,3),
	ay decimal(7,3),
	az decimal(7,3),
	break_y decimal(7,3),
	break_angle decimal(7,3),
	break_length decimal(7,3),
	pitch_type char(2),
	type_confidence decimal(7,3),
	spin_dir decimal(7,3),
	spin_rate decimal(7,3),
	zone integer,
	primary key(game_id, num, id)
);

create table hitchart (
	hit_id bigint not null primary key,
	game_id varchar(30) not null,
	des varchar(25),
	x decimal(7,3),
	y decimal(7,3),
	batter integer,
	pitcher integer,
	type char(1),
	team varchar(1),
	inning integer
);

create table player (
	team varchar(3),
	id integer primary key,
	pos varchar(3),
	type varchar(10),
	first_name varchar(30),
	current_position varchar(3),
	last_name varchar(30),
	jersey_number varchar(2),
	height varchar(5),
	weight integer,
	bats varchar(3),
	throws varchar(3),
	dob varchar(20)
);
